### ISSUE TITLE
Organize April event to train UCI PECE ambassadors

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/design-group#13]
"PECE party" April 25 when I am in Irvine (and maybe coordinate so that Lindsay and maybe even other PECEniks can be around) and run an almost "hackathon" like learning by doing type of training type event for those who want to do PECE (training up students to be "ambassadors") and also working through some of the Figuring out Methods material.

**Comment by ibara** [comment]
Be happy to provide remote support for this.

**Comment by Honoluluskye** [comment]
awesome thanks Brian! Will keep you posted.
*Angela Okune*
angelaokune.me/
+254 (0) 792 632 382 | +1 (808) 358-8563
@honoluluskye | Skype: angela_crandall
